- name: write nginx loadbalancer.conf 
  action: template src=templates/loadbalancer.conf.j2 dest=/etc/nginx/conf.d/{{ item.value.name }}.conf
  with_dict: "{{ loadbalancers }}"
  notify:
    - reload nginx
