- name: remove default.conf
  file:
    state: absent
    path: "/etc/nginx/conf.d/default.conf"

- name: write nginx loadbalancer.conf 
  action: template src=templates/loadbalancer.conf.j2 dest=/etc/nginx/conf.d/{{ item.value.name }}.conf
  with_dict: "{{ loadbalancers }}"
  notify:
    - reload nginx
