- name: creating /usr/share/nginx/webserver directory
  file:
    path: "/usr/share/nginx/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - red
    - blue
    - green
    - yellow

- name: write webserver.html files
  action: template src=templates/webserver.html.j2 dest=/usr/share/nginx/{{ item.value.name }}/index.html
  with_dict: "{{ webservers }}"
    
- name: write nginx webserver.conf files
  action: template src=templates/webserver.conf.j2 dest=/etc/nginx/conf.d/{{ item.value.name }}.conf
  with_dict: "{{ webservers }}"
  notify:
    - reload nginx
