---
- name: creating /usr/share/nginx/{{ item }} 
  file:
  path: /usr/share/nginx/{{ item }}
  state: directory
  mode: 0755
  with_items:
      - "{{ webservers }}"

- name: write webserver.html files
  action: template src=templates/webserver.html.j2 dest=/usr/share/nginx/{{ item }}/index.html
  with_items:
      - "{{ webservers }}"
    
- name: write nginx webserver.conf files
  action: template src=templates/webserver.conf.j2 dest=/etc/nginx/conf.d/{{ item }}.conf
  with_items:
      - "{{ webservers }}"
  notify:
    - reload nginx
