---
default_nginx_error_log_level: "debug"
default_nginx_worker_connections: "512"

webservers:
    blue:
      name: "blue"
      port: 8081
    red:
      name: "red"
      port: 8082
    yellow:
      name: "yellow"
      port: 8083
    green:
      name: "green"
      port: 8084

loadbalancers:
    backend:
      name: "backend"
      port: 80
...
