---
- name: print to stdout
  command: echo "hello"
  register: hello

- debug: 
  msg: "{{ hello.stdout }}"

- debug: 
  msg: "{{ hello.stderr }}"

- debug: 
  msg: "{{ hello.stdout_lines }}"

- name: print nginx -T 
  command: /usr/sbin/nginx -T 
  become: yes
  register: nginx 

- debug: 
  msg: "{{ nginx.stdout }}"

- debug: 
  msg: "{{ nginx.stderr }}"

- debug: 
  msg: "{{ nginx.stdout_lines }}"
