---
- name: print to stdout
  shell: echo "hello"
  register: hello

- debug: 
    msg: "{{ hello.stdout }}"

- debug: 
    msg: "{{ hello.stderr }}"

- debug: 
    msg: "{{ hello.stdout_lines }}"

- name: print nginx -T 
  shell: /usr/sbin/nginx -T 
  become: yes
  register: nginx 

- debug: 
    var: "{{ nginx.to_json }}"
