---
- name: creating /etc/ssl/nginx/webservers directories
  file:
    path: "/etc/ssl/nginx/webservers/{{ item.value.name }}"
    state: directory
    mode: 0755
  with_dict: "{{ webservers }}"

- name: copying {{ item.value.name }} certs
  copy:
    src: "{{ item.value.name }}/{{ item.value.name }}.crt"
    dest: /etc/ssl/nginx/webservers/{{item.value.name }}/{{ item.value.name }}.crt
    owner: root
    group: root
    mode: 0755
  with_dict: "{{ webservers }}"

- name: copying {{ item.value.name }} keys
  copy:
    src: "{{ item.value.name }}/{{ item.value.name }}.key"
    dest: /etc/ssl/nginx/webservers/{{item.value.name }}/{{ item.value.name }}.key
    owner: root
    group: root
    mode: 0755
  with_dict: "{{ webservers }}"

- debug:
    msg: "Writing nginx.conf"

- debug:
    msg: "Reloading nginx"
