---

- name: include ssl
  include_tasks: "ssl.yml"
  when: webservers is defined

- name: include webservers
  include_tasks: "webservers.yml"
  when: webservers is defined

- name: include loadbalancers
  include_tasks: "loadbalancers.yml"
  when: loadbalancers is defined
