---

- name: write nginx webserver.conf files
  action: template src=templates/webserver.conf.j2 dest=/etc/nginx/conf.d/ssl_{{ item.value.name }}.conf
  with_dict: "{{ webservers }}"
  notify:
    - reload nginx

