---
#nginx.conf config file options
default_nginx_error_log_level: "debug"
default_nginx_worker_connections: "512"

cache: "true"
rate_limit: "true"
active_health_checks: "true"


#webservers data dictonary
webservers:
    blue:
      id: "0"
      name: "blue"
      port: 8081
      weight: 1 
      max_conns: 0
      max_fails: 0
      fail_timeout: "60s"
      slow_start: "0s"
      backup: "false"
      down: "false"
    red:
      id: "1"
      name: "red"
      port: 8082
      weight: 1 
      max_conns: 0
      max_fails: 0
      fail_timeout: "60s"
      slow_start: "0s"
      backup: "false"
      down: "false"
    yellow:
      id: "2"
      name: "yellow"
      port: 8083
      weight: 1 
      max_conns: 0
      max_fails: 0
      slow_start: "0s"
      fail_timeout: "60s"
      backup: "false"
      down: "false"
    green:
      id: "3"
      name: "green"
      port: 8084
      weight: 1 
      max_conns: 0
      max_fails: 0
      fail_timeout: "60s"
      slow_start: "0s"
      backup: "false"
      down: "false"

#loadbalancers data dictionary
loadbalancers:
    backend:
      name: "backend"
      port: 80
      lb_method: "least_conn"
      zone_size: "64k"
      sticky_cookie: "false"
...
