---
default_nginx_error_log_level: "debug"
default_nginx_worker_connections: "512"

limit_req_zone: "limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;"

webservers:
    blue:
      name: "blue"
      port: 8081
      ssl_port: 8444
    red:
      name: "red"
      port: 8082
      ssl_port: 8445
    yellow:
      name: "yellow"
      port: 8083
      ssl_port: 8446
    green:
      name: "green"
      port: 8084
      ssl_port: 8447

loadbalancers:
    ssl_backend:
      name: "ssl_backend"
      port: 443 
      lb_method: "least_conn"
      zone_size: "64k"
...
