---
- name: write webserver.html files
  action: template src=templates/webserver.html.j2 dest=/usr/share/nginx/{{ item.value.name }}/index.html
  with_dict: "{{ webservers }}"
  notify:
    - reload nginx

- name: write nginx webserver.conf files
  action: template src=templates/webserver.conf.j2 dest=/etc/nginx/conf.d/{{ item.value.name }}.conf
  with_dict: "{{ webservers }}"
  notify:
    - reload nginx
