---
- name: write webserver.html files
  action: template src=templates/webserver.html.j2 dest=/usr/share/nginx/{{ item.value.name }}/index.html
  with_dict: "{{ webservers }}"
  notify:
    - reload nginx
